version: "3"

services:
  backend:
    build: .
    command: sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - env/.env.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
